### ISSUE TITLE
inference.py

### ISSUE THREAD

**Issue by H-CODE6** [lescientifik/open_brats2020#14]
Hello, please run information Runtimeerror occurs in inference.py : stack expectations each tensor to be equal size, but got [1, 3, 144, 176, 144] at entry 0 and [1, 3, 155, 240, 240] at entry 1. How to solve it?

**Comment by Fazzy101** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/Colab_Notebooks/brats2020/open_brats2020/src/inference.py", line 177, in <module>
    main(arguments)
  File "/content/drive/MyDrive/Colab_Notebooks/brats2020/open_brats2020/src/inference.py", line 106, in main
    generate_segmentations((loader_minmax, loader_zscore), models_list, normalisations_list, args)
  File "/content/drive/MyDrive/Colab_Notebooks/brats2020/open_brats2020/src/inference.py", line 156, in generate_segmentations
    pre_segs = torch.stack(model_preds).mean(dim=0)
RuntimeError: stack expects a non-empty TensorList

How to solve this please?

**Comment by Fazzy101** [comment]
Traceback (most recent call last):
  File "/usr/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/content/drive/MyDrive/Colab_Notebooks/brats2020/open_brats2020/src/inference.py", line 178, in <module>
    main(arguments)
  File "/content/drive/MyDrive/Colab_Notebooks/brats2020/open_brats2020/src/inference.py", line 106, in main
    generate_segmentations((loader_minmax, loader_zscore), models_list, normalisations_list, args)
  File "/content/drive/MyDrive/Colab_Notebooks/brats2020/open_brats2020/src/inference.py", line 157, in generate_segmentations
    pre_segs = torch.stack(model_preds).mean(dim=0)
RuntimeError: stack expects each tensor to be equal size, but got [1, 3, 144, 192, 144] at entry 0 and [1, 3, 155, 240, 240] at entry 1




How to solve this, please?

**Comment by Fazzy101** [comment]
how did u solve it?@H-CODE6

**Comment by ella-2002e** [comment]
I have the same problem. Please tell me how did you solve it?
